//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_restaurant
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string location { get; set; }
        public string password { get; set; }
    
        public virtual tbl_request tbl_request { get; set; }
    }
}
