//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_item
    {
        public int id { get; set; }
        public string name { get; set; }
        public int quantity { get; set; }
        public System.DateTime expire_date { get; set; }
        public int request_id { get; set; }
    
        public virtual tbl_request tbl_request { get; set; }
        public int? RequestID { get; internal set; }
    }
}
