//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_request()
        {
            this.tbl_item = new HashSet<tbl_item>();
        }
    
        public int id { get; set; }
        public System.DateTime req_time { get; set; }
        public System.DateTime col_time { get; set; }
        public string status { get; set; }
        public int restaurent_id { get; set; }
        public int employee_id { get; set; }
    
        public virtual tbl_employee tbl_employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_item> tbl_item { get; set; }
        public virtual tbl_restaurant tbl_restaurant { get; set; }

       
    }
}
